INCS = \
        -I/home/gsohler/git/CMSIS_5/CMSIS/Core/Include \
	-I../source/compoment/adc \
	-I../source/compoment/i2c \
	-I../source/compoment/sdio \
	-I../source/compoment/sdio/sd_card/inc \
	-I../source/compoment/spi \
	-I../source/compoment/uart \
	-I../source/compoment/Utility \
	-I../source/drivers/board \
	-I../source/drivers/library \
	-I../source/drivers/library/inc \
	-I../source/framework/cores \
	-I../source/framework/usb \
	-I../source/framework/variants \
	-I../source/main \
	-I../source/main/hdsc32core \
	-I../source/Marlin \
	-I../source/Marlin/src \
	-I../source/Marlin/src/pins \
	-I../source/Marlin/src/core \
	-I../source/Marlin/src/feature \
	-I../source/Marlin/src/feature/bedlevel \
	-I../source/Marlin/src/feature/bedlevel/abl \
	-I../source/Marlin/src/feature/bedlevel/mbl \
	-I../source/Marlin/src/feature/bedlevel/ubl \
	-I../source/Marlin/src/feature/digipot \
	-I../source/Marlin/src/feature/leds \
	-I../source/Marlin/src/feature/mmu \
	-I../source/Marlin/src/feature/password \
	-I../source/Marlin/src/gcode \
	-I../source/Marlin/src/HAL \
	-I../source/Marlin/src/HAL/shared \
	-I../source/Marlin/src/HAL/shared/backtrace \
	-I../source/Marlin/src/HAL/STM32 \
	-I../source/Marlin/src/HAL/STM32/tft \
	-I../source/Marlin/src/HAL/STM32/inc \
	-I../source/Marlin/src/inc \
	-I../source/Marlin/src/lcd \
	-I../source/Marlin/src/lcd/dogm \
	-I../source/Marlin/src/lcd/dogm/fontdata \
	-I../source/Marlin/src/lcd/dwin \
	-I../source/Marlin/src/lcd/language \
	-I../source/Marlin/src/lcd/menu \
	-I../source/Marlin/src/lcd/menu/game \
	-I../source/Marlin/src/libs \
	-I../source/Marlin/src/module \
	-I../source/Marlin/src/module/stepper \
	-I../source/Marlin/src/module/thermistor \
	-I../source/Marlin/src/pins \
	-I../source/Marlin/src/pins/stm32f1 \
	-I../source/Marlin/src/sd \
	-I../source/Marlin/src/sd/usb_flashdrive \
	-I../source/Marlin/src/sd/usb_flashdrive/lib-uhs2 \
	-I../source/Marlin/src/lcd/extui \
	-I../source/Marlin/src/lcd/extui/lib/anycubic \
	-I../source/Marlin/src/lcd/extui/lib/dgus \
	-I../source/Marlin/src/lcd/extui/lib/dgus/fysetc \
	-I../source/Marlin/src/lcd/extui/lib/dgus/hiprecy \
	-I../source/Marlin/src/lcd/extui/lib/dgus/origin \
	-I../source/Marlin/src/lcd/extui/lib/ftdi_eve_touch_ui \
	-I../source/Marlin/src/lcd/extui/lib/ftdi_eve_touch_ui/archim2-flash \
	-I../source/Marlin/src/lcd/extui/lib/ftdi_eve_touch_ui/ftdi_eve_lib \
	-I../source/Marlin/src/lcd/extui/lib/ftdi_eve_touch_ui/ftdi_eve_lib/basic \
	-I../source/Marlin/src/lcd/extui/lib/ftdi_eve_touch_ui/ftdi_eve_lib/extended \
	-I../source/Marlin/src/lcd/extui/lib/ftdi_eve_touch_ui/ftdi_eve_lib/extended/unicode \
	-I../source/Marlin/src/lcd/extui/lib/ftdi_eve_touch_ui/ftdi_eve_lib/extras \
	-I../source/Marlin/src/lcd/extui/lib/ftdi_eve_touch_ui/language \
	-I../source/Marlin/src/lcd/extui/lib/ftdi_eve_touch_ui/screens \
	-I../source/Marlin/src/lcd/extui/lib/ftdi_eve_touch_ui/theme \
	-I../source/Marlin/src/lcd/extui//lib/mks_ui \
	-I../source/Marlin/src/lcd/HD44780 \
	-I../source/Marlin/src/sd/usb_flashdrive/lib-uhs3/dyn_SWI \
	-I../source/Marlin/src/sd/usb_flashdrive/lib-uhs3/UHS_host \
	-I../source/Marlin/src/sd/usb_flashdrive/lib-uhs3/UHS_host/UHS_BULK_STORAGE \
	-I../source/Marlin/src/sd/usb_flashdrive/lib-uhs3/UHS_host/USB_HOST_SHIELD \
	-I../source/Marlin/src/libs/heatshrink \
	-I../source/Marlin/src/libs/L64XX \
	-I../source/Marlin/src/lcd/dogm/status \
	-I../source/Marlin/src/lcd/dwin/e3v2 \
 	-I../source/Marlin/src/lcd/extui/lib/anycubic_chiron \
	-I../source/Marlin/src/lcd/extui/lib/anycubic_dgus \
	-I../source/Marlin/src/lcd/extui/lib/anycubic_i3mega \
	-I../source/Marlin/src/lcd/tft \
	-I../source/Marlin/src/lcd/tft_io \
	-I../source/Marlin/src/lcd/TFTGLCD \
	-I../source/Marlin/src/lcd/touch \
	-I../source/Marlin/src/module/stepper/source \
	-I../source/framework/TMCStepper \
	-I../source/framework/TMCStepper/source \
	-I../source/arduino \
	-I../source/board \
	-I../source/FatFs \
	-I../source/framework/SoftwareSerial 
DEFINES= -D__LONGLONG="long long" \
	-DHC32F46x \
	-DUSE_DEVICE_DRIVER_LIB \
	-D__TARGET_FPU_VFP \
	-D__FPU_PRESENT=1 \
	-DARM_MATH_CM4 \
	-DARM_MATH_ROUNDING \
	-D__MPU_PRESENT=1 \
	-DSTM32_HIGH_DENSITY \
	-DARDUINO_ARCH_STM32F1 \
	-D__CC_ARM \
	-D ARM_MATH_MATRIX_CHECK \
	-DARDUINO_ARCH_STM32 \
	-DRAMSTART=0x1fff8000 \
	-DRAMEND=0x1fffffff


CPPSOURCES=	\
		../source/Marlin/src/sd/cardreader.cpp \
		../source/Marlin/src/HAL/STM32/eeprom_sdcard.cpp

CPPFLAGS=-mcpu=cortex-m7 -mtune=cortex-m7 -mthumb -Og -fomit-frame-pointer -falign-functions=16 -ffunction-sections -fdata-sections -fno-common -flto -mfloat-abi=hard -mfpu=fpv5-d16  -Wall -Wextra -Wundef -MD -MP

OBJDIR=./obj

ALLSOURCES      := $(CSOURCES) $(CPPSOURCES)
VPATH  := $(sort  $(dir $(ALLSOURCES)))

CPPOBJECTS  := $(addprefix $(OBJDIR)/, $(notdir $(CPPSOURCES:.cpp=.o)))

OBJECTS = $(CPPOBJECTS)

CPPC=arm-none-eabi-g++

$(CPPOBJECTS) : $(OBJDIR)/%.o : %.cpp Makefile
	$(CPPC) -c $(CPPFLAGS) $(INCS) $(DEFINES)  $< -o $@

all:	$(OBJECTS)

clean:
	rm -rf obj/*

test:
	echo $(CPPOBJECTS)
	echo $(CPPSOURCES)
	echo $(ASOURCES)
	echo $(SOURCESPATHS)


